name: update

on:
  workflow_dispatch:
  schedule:
    # every 7 days
    - cron: '0 0 */7 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Update
        run: pnpm run start
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update'
